#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/executor/forecast
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/forecast/Makefile$
#
#-------------------------------------------------------------------------

subdir = src/backend/forecast
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = algorithm.o
SUBDIRS = methods modelindex modelGraph

include $(top_srcdir)/src/backend/common.mk
