#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/executor/forecast/methods
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/executor/forecast/Makefile$
#
#-------------------------------------------------------------------------


subdir = src/backend/forecast/methods
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS =  medium.o gnuR.o linreg.o additiveDec.o forecastUtilitys.o commonARIMA.o armodel.o ExpSmooth.o

include $(top_srcdir)/src/backend/common.mk
