package components.listeners;
/**
 * This interface contains a list of all SQL92 Keywords, the SQLKeywordLineStyleListener 
 * will format with a style
 * @author Felix Beyer
 * @date   08.05.2006
 *
 */
public interface Keywords {
	
	// the reserved keywords
	// derived from the javadoc for sqlgrammar.jj
	// see bottom of document under reservedKeyword part
	
	static final String[] keywords ={
	"ADD","AGGREGATION","ALGORITHM","ALL","ALLOCATE","ALTER","AND","ANY","~","APPROXIMATE","ARE","AS","ASOF","ASC","ASSERTION",
	"AT","AUTHORIZATION","AVG","BEGIN","BETWEEN","BIT","BOTTOMUP","BITSETORAGGR","BITSETANDAGGR",
	"BITSETXORAGGR","BITSETAPPENDAGGR","BOTH","BY","CASCADE","CASCADED","CASE",
	"CAST","CHAR","CHARACTER","CHECK","CLOSE","COLLATE","COLLATION","COLUMN","COMMIT","COMPLETE",
	"CONNECT","CONNECTION","CONFIDENCE","CONSTRAINT","CONSTRAINTS","CONTINUE","CONVERT","CORRESPONDING",
	"COUNT","CREATE","CUBE","CURRENT","CURRENT_DATE","CURRENT_TIME","CURRENT_TIMESTAMP",
	"CURRENT_USER","CURSOR","DATA","DEALLOCATE","DEC","DECIMAL","DECLARE","_DEFAULT",
	"DEFERRABLE","DEFERRED","Disagscheme","Disaggscheme","DELETE","DEMAND","DESC","DESCRIBE","DIAGNOSTICS","DISABLE","DISCONNECT",
	"DISTINCT","DOUBLE","DROP","ELSE","ENABLE","END","ENDEXEC","ESCAPE","EXCEPT","EXCEPTION",
	"EXEC","EXECUTE","EXISTS","EXTERNAL","FALSE","FAST","FORCE","FETCH","FILL","FILLING","FIRST","FLOAT","FOR","FORECAST",
	"FOREIGN","FOUND","FROM","FULL","FUNCTION","FUNCTIONS","GET","GET_CURRENT_CONNECTION","GLOBAL",
	"GO","GOTO","GRANT","GREEDY","GROUP","HAVING","HOUR","IDENTITY","IMMEDIATE","IN","INDICATOR",
	"INITIALLY","INNER","INOUT","INPUT","INSENSITIVE","INSERT","INT","INTEGER",
	"INTERSECT","INTERVAL","INTO","IS","ISOLATION","JOIN","KEY","LAST","LEFT","LIKE","LOCAL",
	"LOWER","MANAGED","MATCH","MAX","METHOD","MODELGRAPH","MESSAGE_TEXT","MIN","MINUTE","MODEL","NATIONAL","NATURAL","NCHAR","NVARCHAR",
	"NEXT","NO","NOT","NULL","NULLIF","NUMBER","NUMERIC","OF","ON","ONLINE","ONLY","OPEN","OPTIMIZATION","OPTION","OR",
	"ORDER","OUT","OUTER","OUTPUT","OVER","OVERLAPS","PAD","PARAMETERS","PARTIAL","%","PERCENT","PREPARE","PRESERVE",
	"PRIMARY","PRIOR","PRIVILEGES","QUERY","PAGES","PROCEDURE","PUBLIC","READ","RESTORE","REAL","REFERENCES",
	"REFRESH","RELATIVE","REPEATABLE","RESTRICT","REVOKE","RIGHT","ROLLBACK","ROLLUP","ROWS","SAMPLE","SCHEMA","SCROLL",
	"SECOND","SELECT","SESSION_USER","SET","SIGNAL","SIZE","SMALLINT","SOME","STORE","SPACE","SQL","SQLCODE",
	"SQLERROR","SQLSTATE","STUB","SUBSTRING","SUM","SYSTEM","VARIANCE","SYSTEM_USER","TABLE",
	"TEMPORARY","TIMEZONE_HOUR","TIMEZONE_MINUTE","TOPDOWN","TO","TRAINING","TRAINING_DATA","TRANSACTION","TRANSLATE",
	"TRANSLATION","TUPLES","TRUE","UNION","UNIQUE","UNKNOWN","UPDATE","UPPER","USER","USING",
	"VALUES","VARCHAR","VARYING","VIEW","WHENEVER","WHERE","WITH","WORK","WRITE","WITHOUT",
	"YEAR","BOOLEAN","CALL","EXPLAIN","LONGINT","LTRIM","RTRIM","SUBSTR","STORAGE" };
}
