#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/btree
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/forecast/modelindex/btree/Makefile,v 1.23 2008/02/19 10:30:08 petere Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/forecast/modelindex/btree
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = btree.o

include $(top_srcdir)/src/backend/common.mk
