#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/btree
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/backend/forecast/modelindex/hashtable/Makefile,v 1.23 2008/02/19 10:30:08 petere Exp $
#
#-------------------------------------------------------------------------

subdir = src/backend/forecast/modelindex/hashtable
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = hashtable.o hashtable_utility.o hashtable_itr.o

include $(top_srcdir)/src/backend/common.mk
