#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/forecast/modelindex
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/forecast/modelindex/Makefile$
#
#-------------------------------------------------------------------------

subdir = src/backend/forecast/modelindex
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = modelIndex.o
SUBDIRS = btree hashtable

include $(top_srcdir)/src/backend/common.mk