#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/forecast/modelindex
#
# IDENTIFICATION
#    $PostgreSQL: pgsql/src/forecast/modelindex/Makefile$
#
#-------------------------------------------------------------------------

subdir = src/backend/forecast/modelGraph
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = modelGraph.o modelGraphReceiver.o greedyAlgorithm.o

include $(top_srcdir)/src/backend/common.mk
